### ISSUE TITLE
NPM Wran OldVersion

### ISSUE THREAD

**Issue by KThantZin** [iosiro/baserunner#11]
I can't use npm  install it show like this
![IMG_20211221_221139](https://user-images.githubusercontent.com/25900266/146957729-af093e23-8222-41ea-b133-d4ffebbfec9e.jpg)

**Comment by dmyates** [comment]
Hi @KThantZin, what versions of Node and NPM are you using? Maybe try deleting `package-lock.json` and running `npm install` again.
