### ISSUE TITLE
main.js 404 not found

### ISSUE THREAD

**Issue by jainiresh** [iosiro/baserunner#13]
On startup, main.js request is not found

**Comment by dmyates** [comment]
Hi jainiresh, could you please describe the error you encounter in more detail?

**Comment by jainiresh** [comment]
Hi David,
I cloned the git tool and when i started it using npm start, it started the
tool in my local host:3000.
Inspite of getting started, the app did not work.
When i checked my Requests made in the browser tab, i could see that a 404
ERROR request was present on the start of the app.

It stated the file main.js was not found.

I have attached the screenshot for reference.

Regards

**Comment by dmyates** [comment]
Thank you. As per the readme, please make sure to run `npm run build` before `npm start`.

**Comment by jainiresh** [comment]
Sure, I will do that.

**Comment by jainiresh** [comment]
Awesome, thanks!
