### ISSUE TITLE
Support Google authentication

### ISSUE THREAD

**Issue by dmyates** [iosiro/baserunner#2]
It doesn't look like too much of a pain:

https://firebase.google.com/docs/auth/web/google-signin

**Comment by saligrama** [comment]
Have a janky implementation up and working: https://github.com/saligrama/baserunner

I'm definitely not the most familiar with node/stimulus/google oauth, and would appreciate any feedback, specifically with regards to

* dynamically setting google oauth client id
* not have to click a separate button to callback to the stimulus controller login function once the google login succeeds

**Comment by dmyates** [comment]
Thanks for this @saligrama! I'll take a look in the next few days and get back to you.

**Comment by saligrama** [comment]
Any update @dmyates? It's been a while, let me know if/what changes I should make!

**Comment by dmyates** [comment]
> Any update @dmyates? It's been a while, let me know if/what changes I should make!

Hey @saligrama, sorry for the delayed response. The Google Auth itself works quite well, good job on that, but I have a couple of requests:

1. For some reason your fork's commit history is totally different from my main repo, so there's no easy way to create a PR. I could work around this by cherry picking your commits, but it's a bit messy. Could you fix your repo so that we can create a PR?
2. I'm not really keen on having users edit the index.html file. Do you think there's a way we could have that change handled interactively on the frontend?

**Comment by saligrama** [comment]
Thanks @dmyates for the review. I'll try to figure out what happened to the git history, it's entirely possible that few-months-ago me did something stupid with git.

As far as the index.html change, the only possibility I see is to ask for the client ID upfront and generate a temporary page that embeds that client ID provided by the user. Is that a workable solution for you? If so I'll try to make that change shortly.

**Comment by saligrama** [comment]
@dmyates both issues fixed and PR created #12

**Comment by dmyates** [comment]
Thanks again for your work!
